### ISSUE TITLE
Version 3 to 4 (and .scss to .sass)

### ISSUE THREAD

**Issue by james-criscuolo** [shannonmoeller/reset-css#14]
I'm using webpack 4.10.2 with sass-loader 6.0.7. After updating my include for the new version to have `/sass`, my build now fails with:

```
ERROR in Module build failed:
   License: none (public domain)
                                  ^
      Invalid CSS after "...blic domain) */": expected 1 selector or at-rule, was "*/ {}"
      in (myBuildPath)/node_modules/reset-css/sass/_reset.sass (line 3, column 36)
```
I didn't inspect the file terribly closely, but I believe the only real difference between version 3 and version 4 is that the extension changed. If I manually switch the extension back to `.scss`, the build succeeds.

Lastly, plugging the file into https://www.sassmeister.com/ switches the comment to look like this:

```
/* http://meyerweb.com/eric/tools/css/reset/
 * v4.0 | 20180602
 * License: none (public domain)

html, body, div, span, applet, object, iframe,
```
but then upon compile, it switches to 
```
/* http://meyerweb.com/eric/tools/css/reset/
 * v4.0 | 20180602
 * License: none (public domain) */
html, body, div, span, applet, object, iframe,
```
(The comment closing characters being the important difference). Manually altering the `.sass` file to have this comment style ends up breaking the build further down the file (at `time, mark, audio, video {`), which leads me to believe the extension switch may have been by mistake.

Was the change from `.scss` to `.sass` intentional? And if so, is there anything else I should try here?

**Comment by shannonmoeller** [comment]
Total bug! Thank you! Corrected back to `.scss` and released as v4.0.1. My apologies.
