### ISSUE TITLE
why not reset the :-webkit-any(article,aside,nav,section) h1 

### ISSUE THREAD

**Issue by klren0312** [shannonmoeller/reset-css#16]
```css
:-webkit-any(article,aside,nav,section) h1 
```
not be reset

**Comment by shannonmoeller** [comment]
Sorry, I’m not sure what you’re asking.

**Comment by klren0312** [comment]
I find I use <h1> in the <section> , it do not has the style, because the chrome default style`:-webkit-any(article,aside,nav,section) h1 `
so  reset.css can add it
