### ISSUE TITLE
`menu` selector is present twice in first rule

### ISSUE THREAD

**Issue by JackNUMBER** [shannonmoeller/reset-css#21]
There is the `menu` two time in the first rule:

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, `menu`, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
main, `menu`, nav, output, ruby, section, summary,
time, mark, audio, video { ... }

The code quality check Sonarqube reports it as code-smell : https://rules.sonarsource.com/css/RSPEC-4666/

Introduced by #17

**Comment by shannonmoeller** [comment]
PR welcome. :)

**Comment by JackNUMBER** [comment]
Sure! 👉 #22

**Comment by shannonmoeller** [comment]
Thank you!
