### ISSUE TITLE
Cannot import SCSS version

### ISSUE THREAD

**Issue by thejamespower** [shannonmoeller/reset-css#6]
Having the css and scss version named the same causes sass to throw a wobbly making it impossible to import the scss version in this set up.

`@import '_reset'` 
is invalid and results in 
`Error: File to import not found or unreadable`

The correct method:
`@import 'reset'`
results in 
`Error: It's not clear which file to import for @import`
As sass doesn't know whether to import the css or sass version.

**Comment by shannonmoeller** [comment]
I need a little more context. I would expect your example to include the module name like so:

``` sass
@import 'reset-css/reset';
```

What installation method have you used and how have you configured the build task? Are you using libsass or the Ruby version? The `_reset.scss` file only exists because Ruby Sass could not import a regular CSS file.

**Comment by shannonmoeller** [comment]
If you're using libsass, have you tried using the extension to disambiguate?:

``` scss
@import '../path/to/reset-css/reset.css';
```

http://stackoverflow.com/a/36166487

**Comment by shannonmoeller** [comment]
@thejamespower Were you able to get it working?

**Comment by thejamespower** [comment]
Hi @shannonmoeller, apologies for the late reply. I'm using libsass (through node-sass). As far as I understand it, to import a SCSS/CSS file in SCSS you have to use:

```
@import 'filename'; // without extension
```

However if you have a CSS and SCSS doc' with the same name, SASS does not know which to import, which is why it throws an error.

**Comment by shannonmoeller** [comment]
The only way I see around this is to put each type of file into its own directory:

```
./
|- css/
|  `- reset.css
|
|- less/
|  `- reset.less
|
`- scss/
   `- _reset.scss
```

This would be a breaking change for existing users and would change the solution from:

``` scss
@import '../bower_components/reset-css/_reset.scss';
```

to:

``` scss
@import '../bower_components/reset-css/scss/reset';
```

The "breaking" part of that change is what concerns me.

**Comment by shannonmoeller** [comment]
Closing this for now as it's been over a year with no feedback or one-ups from others. If it's still a big issue, I'm happy to reopen.
