### ISSUE TITLE
outline styles reset

### ISSUE THREAD

**Issue by hozefaj** [shannonmoeller/reset-css#9]
Although this is supposed to be a copy of reset CSS, but it is possible to add reset styles for `outline` property for `focus` state. Happy to send PR across.

**Comment by shannonmoeller** [comment]
This is a copy of the newest reset ([20110126](http://meyerweb.com/eric/tools/css/reset/)) which intentionally does not include the outline reset for accessibly reasons:

https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/
